name: "composer.json normalizer"

on:
  workflow_call:
    secrets:
      token:
        description: GitHub classic token with repo and workflow scopes
        required: false

jobs:
  normalize:
    name: composer-normalize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token || github.token }}
          run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action:latest

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: composer.json
          commit_message: "Normalize composer.json (CI)"
