name: rector

on:
  workflow_call:
    inputs:
      composer-command:
        description: Composer command to run.
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      os:
        description: Os to test, separated by comma.
        required: true
        type: string
      php:
        description: PHP versions to test, separated by comma.
        required: true
        type: string

    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  rector:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Set env BRANCH event `pull_request`.
        if: github.event_name == 'pull_request'
        run: echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Set env BRANCH `event push`.
        if: github.event_name == 'push'
        run: echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout.
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ env.BRANCH }}

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Update composer.
        run: composer self-update

      - name: Install dependencies with composer.
        run: ${{ inputs.composer-command }}

      - run: vendor/bin/rector process --ansi

      - name: Check for Rector modified files.
        id: rector-git-check
        run: echo ::set-output name=modified::$(if git diff --exit-code --no-patch; then echo "false"; else echo "true"; fi)

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "[ci-review] Apply changes from Rector action."
            commit_author: "rector-bot"
            commit_user_email: "rector@yiiframework.com"
